"""empty message

Revision ID: 6ae7da744241
Revises: e304e393cb48
Create Date: 2024-04-12 02:55:20.549115

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ae7da744241'
down_revision = 'e304e393cb48'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('people',
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.Column('person_name', sa.String(length=250), nullable=True),
    sa.Column('weight', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('person_id')
    )
    op.drop_table('character')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('character',
    sa.Column('character_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('character_name', sa.VARCHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('weight', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('height', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('character_id', name='character_pkey')
    )
    op.drop_table('people')
    # ### end Alembic commands ###
